### ISSUE TITLE
File sink question

### ISSUE THREAD

**Issue by mwk088** [ghostop14/gr-filerepeater#9]
@ghostop14 
This is not an issue, but rather a question about a feature being available with the gr-filerepeater.  I need to make a long collect of samples, and they must be iq.  As you know this would become quite large, and I can't let the file size grow too monsterous, so I was hoping that the advanced file_sink block would allow me to collect and continuously write over the file, saving only the file size designated in the block.  Unfortunately, I see that the file size designator allows it to write to the file until the file size is reached then it stops writing.  

How hard would it be to add the feature I am asking for?  If you point me to the correct location, I could possibly modify it locally.

Thank you

Mark

**Comment by ghostop14** [comment]
Hi mwk088, so I do think you have a couple of quick/easy options.  First option may be to look at the state timer block in the OOT.  You could Just set a trigger and delay time such that every n minutes it sends a stop then a start.  That could make the existing block create separate files.  Another option for really long recordings if you're okay with the loss of resolution is to convert float complex down to interleaved int16 or interleaved byte.  int16 would get you a 50% "compression", and byte would get you a 75% "compression".   For instance, Complex->IChar before writing bytes, then source to IChar to Complex to read it back in.  gr-grnet has some other blocks to do the same with int16 I don't think is in GR core.  If you have a good SNR in your signal, the loss of bits shouldn't impact downstream processing too much.  Int16 should be pretty safe since most SDRs (e.g. USRPs, Airspys are 12-bit and hackrf, rtlsdr are 8-bit) don't sample at any better than 12-bit resolution and map up to float complex anyway.

**Comment by mwk088** [comment]
Thanks for the suggestions and will look to implement them today.  Btw, the enhanced gnuradio blocks you develop are outstanding.  I am looking to take advantage of sparrow-wifi among others in the future.

Mark

**Comment by ghostop14** [comment]
Thanks mwk088.  Let me know how you make out.

**Comment by mwk088** [comment]
ghostop14,

I ended up using your suggestion of using the state timer block, and it is working out great.  While running my application, I am periodically saving the data and allowing the file to change names.  I have bash script running in the background checking for the older raw iq files and deleting them accordingly, as to not have 1,000's of files taking up disk space.

Thanks again

Mark

**Comment by ghostop14** [comment]
Awesome!
